- README.md
- build.sc
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/consumer/http/PubsubHttpConsumer.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/consumer/http/PubsubHttpConsumerConfig.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/consumer/http/internal/HttpPubsubReader.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/consumer/http/internal/PubsubSubscriber.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/http/oauth/DefaultTokenProvider.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/http/oauth/GoogleOAuth.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/producer/http/BatchingHttpPubsubProducer.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/producer/http/HttpPubsubProducer.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/producer/http/internal/DefaultHttpPublisher.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/consumer/http/Example.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/producer/http/ExampleBatching.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/producer/http/ExampleEmulator.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/producer/http/ExampleGoogle.scala
The main change is that 
```scala
Stream.repeatEval(reader.read)
```
becomes
```scala
Stream
.emit(reader.read)
.repeat
.covary[F]
.mapAsyncUnordered(config.readConcurrency)(identity)
```
Other changes in this PR:
- better error handling and logging for asynchronous queues (acks and nacks)
- actually parse errors from PubSub
- do not depend on an implementation of a logger, instead make users provide it
> Make HTTP consumer concurrent, make it configurable

- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/producer/http/PubsubHttpProducerConfig.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/producer/http/internal/DefaultHttpPublisher.scala
Currently, if the OAuth token retrieval fails, the next time it will be retry is only in half an hour.
This PR makes it possible to configure retry logic for token retrieval.
New params are available:
```
oauthTokenFailureRetryDelay: FiniteDuration = 0.millis,
oauthTokenFailureRetryNextDelay: FiniteDuration => FiniteDuration = _ => 5.minutes,
oauthTokenFailureRetryMaxAttempts: Int = Int.MaxValue,
```
> Retry OAuth token refresh upon failure, configurable.

- README.md
- build.sc
- fs2-google-pubsub-grpc/src/main/scala/com/permutive/pubsub/producer/grpc/internal/DefaultPublisher.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/producer/http/BatchingHttpPubsubProducer.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/producer/http/internal/BatchingHttpPublisher.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/producer/http/internal/DefaultHttpPublisher.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/producer/http/ExampleBatching.scala
- fs2-google-pubsub/src/main/scala/com/permutive/pubsub/producer/AsyncPubsubProducer.scala
- fs2-google-pubsub/src/main/scala/com/permutive/pubsub/producer/Model.scala
- fs2-google-pubsub/src/main/scala/com/permutive/pubsub/producer/PubsubProducer.scala
Outer effect represents publishing, inner awaiting result of publish.
Also:
* Add new `MessageId` class and make publishers return this, not `String`
* Remove `AsyncRecord` and `SimpleRecord` as both can be a `Record` now
* Update `cats-effect` to `1.3.0`
> Change AsyncPubsubProducer to return nested effects

- .editorconfig
- README.md
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/producer/http/internal/BatchingHttpPublisher.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/producer/http/internal/DefaultHttpPublisher.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/producer/http/ExampleBatching.scala
- fs2-google-pubsub/src/main/scala/com/permutive/pubsub/producer/AsyncPubsubProducer.scala
- fs2-google-pubsub/src/main/scala/com/permutive/pubsub/producer/Model.scala
Now the callback includes information about if the publish succeeded or
failed.
Also rename nested effect async producing to produce and produceMany.
Makes naming more consistent with previous release version.
> Add callback async publishing back to AsyncPubsubProducer

- build.sc
- fs2-google-pubsub-grpc/src/main/scala/com/permutive/pubsub/consumer/grpc/internal/PubsubSubscriber.scala
Change queue `offer` to `put` as `put` blocks.
`offer` returns a `boolean` indicating if the insert was successful or
not. Possibly what has been happening in consumers is that under high
load the insert has been unsuccessful, which means the `ack` and `nack`
are discarded entirely. The message was therefore lost (missed acks).
Testing indicates this may not alleviate the problem entirely, useful
to come up with a minimal case showing behaviour...
> Possibly lower missing acks when under heavy load in gRPC variant

- .travis.yml
- build.sc
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/consumer/http/Example.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/producer/http/ExampleBatching.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/producer/http/ExampleEmulator.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/producer/http/ExampleGoogle.scala
This includes the commit from #16 and updates dependencies for 2.13.0.
A couple of notes:
* cats-effect now includes a nice `Blocker` API that manages its own cached thread pool, so I've switched to using that.
* I'm using `CrossSbtModule` instead of `CrossScalaModule` + `SbtModule`, since that combo was breaking the test module paths.
* I've added a test module for `fs2-google-pubsub-grpc` so that example code gets included in the build.
* I've added `mill __.test` to Travis so the example projects get compiled.
r? @CremboC
> Updates for 2.13.0

- build.sc
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/consumer/http/Example.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/producer/http/ExampleBatching.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/producer/http/ExampleEmulator.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/producer/http/ExampleGoogle.scala
I jumped the gun on 0.14.0-M1—it turns out we need another set of dependency updates before Cats 2.0.0. This PR temporarily drops the Scala 2.13 build and updates all other dependencies to the latest non-milestone or RC versions.
> Temporarily drop 2.13; update dependencies to latest final releases

- .travis.yml
- build.sc
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/consumer/http/Example.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/producer/http/ExampleBatching.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/producer/http/ExampleEmulator.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/producer/http/ExampleGoogle.scala
There's a new http4s 0.12 milestone now, so we could do a milestone release with this PR.
~~This doesn't help us much since we can't update fs2 or reintroduce 2.13 until http4s 0.21.0 is out, but these updates are safe.~~
> Update Cats and other dependencies

- .scalafmt.conf
See #28 for explanation. I don't really like the `edition` approach, personally, so I'm just rolling back to 2.2.1 in the hope that the Scalafmt maintainers will decide either to make this configurable soon or to change back the default.
> Back to Scalafmt 2.2.1

- project/Dependencies.scala
The artifact coordinates changed, so Scala Steward couldn't do this.
> Update to scalatestplus-scalacheck release

- fs2-google-pubsub-grpc/src/main/scala/com/permutive/pubsub/consumer/grpc/internal/PubsubSubscriber.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/consumer/http/internal/HttpPubsubReader.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/consumer/http/internal/PubsubSubscriber.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/producer/http/internal/DefaultHttpPublisher.scala
The complete message body is now logged rather than just the
jsoniter-scala decoding error which only includes the first few
characters of the body.
Also fixes an unhandled error that was thrown in an EntityDecoder.
> Improve HTTP error logs when PubSub returns an invalid response

- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/consumer/http/PubsubHttpConsumer.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/consumer/http/internal/PubsubSubscriber.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/consumer/http/Example.scala
It looks like GCP PubSub can be flaky and sometimes returns 502 errors.
This issue has already been spotted in libraries [like this one](https://github.com/googleapis/nodejs-storage/issues/1233), and the solution was [to add retries](https://github.com/googleapis/nodejs-storage/releases/tag/v5.7.3).
My proposal is to add the http4s `Retry` middleware to the `httpClient` that gets passed in the `PubsubSubscriber`.
All of the http endpoints the client hits do not conform to REST idepotency and retriability standards, therefore we need to set retries also on POST requests.
Even if the endpoints called by the client are POST they are actually idempotent, so it's safe to use retries on them.
> consumer retries all (retriable) requests to pubsub

- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/consumer/http/PubsubHttpConsumer.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/consumer/http/internal/HttpPubsubReader.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/consumer/http/internal/PubsubSubscriber.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/http/oauth/DefaultTokenProvider.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/http/oauth/InstanceMetadataOAuth.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/producer/http/BatchingHttpPubsubProducer.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/producer/http/HttpPubsubProducer.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/producer/http/internal/DefaultHttpPublisher.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/PubSubSpec.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/consumer/http/Example.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/producer/http/ExampleBatching.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/producer/http/ExampleEmulator.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/producer/http/ExampleGoogle.scala
Use GCP instance metadata to retrieve an access token
Ported some of our internal code (that we should open source) for obtaining the token.
Discussed with @CremboC how best to do this without a large refactor, considering CE3 is pending, opted for making the service account path optional and breaking the API :/
Once we're happy with this, I'll cut another CE2 release and port the changes to CE3 in master.
> Obtain  auth token from metadata

- README.md
- fs2-google-pubsub-grpc/src/main/scala/com/permutive/pubsub/producer/grpc/internal/DefaultPublisher.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/producer/http/internal/BatchingHttpPublisher.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/producer/http/internal/DefaultHttpPublisher.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/producer/http/ExampleBatching.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/producer/http/ExampleEmulator.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/producer/http/ExampleGoogle.scala
- fs2-google-pubsub/src/main/scala/com/permutive/pubsub/producer/AsyncPubsubProducer.scala
- fs2-google-pubsub/src/main/scala/com/permutive/pubsub/producer/Model.scala
- fs2-google-pubsub/src/main/scala/com/permutive/pubsub/producer/PubsubProducer.scala
* `record` is now `data`
* `metadata` is now `attributes`
Example pub/sub doc with these field names: https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#google.pubsub.v1.PubsubMessage
> Rename fields for consistency with GCP schemas

- fs2-google-pubsub-grpc/src/main/scala/com/permutive/pubsub/consumer/grpc/PubsubGoogleConsumer.scala
- fs2-google-pubsub-grpc/src/main/scala/com/permutive/pubsub/consumer/grpc/internal/PubsubSubscriber.scala
- project/plugins.sbt
- Use `Stream.fromEither` instead of manual fold
- Add `NoStackTrace` to `InternalPubSubError`
- Bump `sbt-pgp` to 2.1.2 (replaces #278 which needed formatting)
> Bump dependencies; Minor tweaks before release

- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/consumer/http/internal/PubsubSubscriber.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/producer/http/internal/BatchingHttpPublisher.scala
The `fs2` implementation will be more efficient as it will emit all
elements available in a single chunk.
> Use `Stream.fromQueue*` instead of `Stream.repeatEval(queue.take)`

- fs2-google-pubsub-grpc/src/main/scala/com/permutive/pubsub/consumer/grpc/PubsubGoogleConsumer.scala
- fs2-google-pubsub-http/src/main/scala/com/permutive/pubsub/consumer/http/internal/Model.scala
- fs2-google-pubsub/src/main/scala/com/permutive/pubsub/consumer/ConsumerRecord.scala
Previously `ConsumerRecord` only contained the message data and
discarded any attributes. This PR attaches the attributes in a new field
on `ConsumerRecord`.
> Expose message attributes in `ConsumerRecord`

- .github/workflows/ci.yml
- build.sbt
- fs2-google-pubsub-grpc/src/main/scala/com/permutive/pubsub/consumer/grpc/internal/PubsubSubscriber.scala
- project/Dependencies.scala
- project/plugins.sbt
Update all the things.
fs2 deprecated directly wrapping a `scala.collection.mutable.Buffer` into a `Chunk` so we introduced a wrapper class that implements `java.util.Collection[A]` and delegates to a `Builder[A, Vector[A]]` to avoid copying.
> Dependency updates

- fs2-google-pubsub-grpc/src/main/scala/com/permutive/pubsub/consumer/grpc/PubsubGoogleConsumerConfig.scala
- fs2-google-pubsub-grpc/src/main/scala/com/permutive/pubsub/consumer/grpc/internal/PubsubSubscriber.scala
- project/Dependencies.scala
Please see this issue: https://github.com/permutive-engineering/fs2-google-pubsub/issues/466
This PR exposes the field `minDurationPerAckExtension` and also the field `exactlyOnceDeliveryEnabled` which will automatically adjust `minDurationPerAckExtension` if it is not set.
Note that this is just for the `grpc` client. The `http` client will still have the same error detailed in the issue linked and will require a different solution.
> expose minDurationPerAckExtension and exactlyOnceDeliveryEnabled

- fs2-google-pubsub-grpc/src/main/scala/com/permutive/pubsub/consumer/grpc/PubsubGoogleConsumerConfig.scala
- fs2-google-pubsub-grpc/src/main/scala/com/permutive/pubsub/consumer/grpc/internal/PubsubSubscriber.scala
- fs2-google-pubsub-grpc/src/test/scala/com/permutive/pubsub/GrpcPingPongSpec.scala
- fs2-google-pubsub-grpc/src/test/scala/com/permutive/pubsub/PubSubSpec.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/HttpPingPongSpec.scala
- fs2-google-pubsub-http/src/test/scala/com/permutive/pubsub/PubSubSpec.scala
- project/Dependencies.scala
Please see this issue: https://github.com/permutive-engineering/fs2-google-pubsub/issues/466
This PR exposes the field minDurationPerAckExtension and also the field exactlyOnceDeliveryEnabled which will automatically adjust minDurationPerAckExtension if it is not set.
Note that this is just for the grpc client. The http client will still have the same error detailed in the issue linked and will require a different solution.
> Exactly once delivery GRPC support
